In [21]:
import numpy as np
import nn

def model1():
    model = nn.sequential(
    layers=
    [nn.temp1(),
    nn.convolve3d(shape =(5,1,3,3), mode = 'valid', param = 'he'),
    nn.add(),
    nn.convolve3d(shape=(25,5,3,3), mode = 'valid', param = 'he'),
    nn.add(),
    nn.linear(shape=(25,25), param = 'he'),
    nn.add(),
    nn.sigmoid()]

    )
    return model 

In [22]:
model = model1()
w = np.load('weights81.npy', allow_pickle= True)
model.set_weights(w)

nn:param:he:- param initilized HE random normal
nn:param:he:- param initilized HE random normal
nn:param:he:- param initilized HE random normal


In [23]:
#sanity check
v = model.get_weights()
w[1]==v[1]

array([[[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]]])

In [24]:
state = np.random.randint(0,3,(5,5))  

In [25]:
#model prediction
value = model.forward(state)
print(value)
print(state)
empty = state.flatten()
empty[empty>1] = 1
print(value*empty)
action = np.argmax(value*empty)
print(action)

[0.01075674 0.01105809 0.01092442 0.01093737 0.010568   0.01119443
 0.01089112 0.01098763 0.01125338 0.01083044 0.0112444  0.01099632
 0.0107387  0.24034683 0.0108984  0.01071064 0.01105153 0.01086828
 0.01111477 0.01129754 0.01075182 0.01071709 0.24500147 0.01077291
 0.01047418]
[[2 0 2 1 1]
 [0 1 1 1 0]
 [1 2 0 0 0]
 [0 1 2 1 1]
 [1 0 2 2 1]]
[0.01075674 0.         0.01092442 0.01093737 0.010568   0.
 0.01089112 0.01098763 0.01125338 0.         0.0112444  0.01099632
 0.         0.         0.         0.         0.01105153 0.01086828
 0.01111477 0.01129754 0.01075182 0.         0.24500147 0.01077291
 0.01047418]
22


In [27]:
import pm
import main

player = 1

board = {1:[], 2:[]}
points = {1:0, 2:0}
turn = 0 
hist = [] # history of board positions

# initially all positions belong to blank - set(board[1]) - set(board[2]))
#board[0] = list(set(list(product(range(size), repeat = 2))))

state = np.zeros((pm.size,pm.size))

while(turn<pm.size**2):
    #randMove = board[0][np.random.randint(len(board[0]))]
    print("Enter your move")
    move = input()
    
    stateNew, r = main.go(state,int(move),player)
    player = 3 - player 
    
    print('next state {}, reward = {}'.format(stateNew,r))
    turn+=1
    
    value = model.forward(stateNew)
    empty = state.flatten()
    empty[empty>1] = 1
    action = np.argmax(value*empty)
    state, r = main.go(stateNew,action,player)
    player = 3 - player 
    
    print('next state {}, reward = {}'.format(state,r))
    turn += 1

Enter your move
0


error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
